base:
  - ../../parts/wall_base/internal/tudor_wall_base.
  - .internal.stl
back:
  - ../../parts/window_back/internal.standard/tudor_window_back.
  - .internal.standard.stl
x-min: 2
x-max: 4
y-min: 1 
y-max: 4
result:
  - tudor_window.
  - .internal.standard.stl
external: false
