base:
  - ../../parts/wall_base/internal/tudor_wall_base.
  - .internal.stl
back:
  - ../../parts/wall_back/internal.standard/tudor_wall_back.
  - .internal.standard.stl
x-min: 1
x-max: 4
y-min: 1
y-max: 4
result:
  - tudor_wall.
  - .internal.standard.stl
external: false
